version: '3.8'

services:
  backend:
    build: 
      context: .
      target: backend
    container_name: playstorm-backend
    ports:
      - "4000:4000"
    env_file:
      - ./apps/backend/.env
    restart: always

  frontend:
    build: 
      context: .
      target: frontend
    container_name: playstorm-frontend
    env_file:
     - ./apps/frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always