export const EDITOR_OPTIONS = {
    colors: [
        { label: "Default", value: "text-white", hex: "#FFFFFF" },
        { label: "Black", value: "text-black", hex: "#000000" },
        { label: "Red", value: "text-red-500", hex: "#ef4444" },
        { label: "Blue", value: "text-blue-500", hex: "#3b82f6" },
        { label: "Green", value: "text-green-500", hex: "#22c55e" },
        { label: "Yellow", value: "text-yellow-400", hex: "#facc15" },
        { label: "Orange", value: "text-orange-500", hex: "#f97316" },
        { label: "Purple", value: "text-purple-500", hex: "#a855f7" },
        { label: "Pink", value: "text-pink-500", hex: "#ec4899" },
        { label: "Cyan", value: "text-cyan-400", hex: "#22d3ee" },
    ],
    fontSize: [
        { label: "8", value: 8 },
        { label: "12", value: 12 },
        { label: "16", value: 16 },
        { label: "20", value: 20 },
        { label: "24", value: 24 },
        { label: "28", value: 28 },
        { label: "32", value: 32 },
        { label: "36", value: 36 },
        { label: "48", value: 48 },
        { label: "64", value: 64 },
    ],
    backgroundColor: [
        { label: "Default", value: "inherit", hex: "transparent" },
        { label: "Black", value: "bg-black", hex: "#000000" },
        { label: "White", value: "bg-white", hex: "#FFFFFF" },
        { label: "Red", value: "bg-red-500", hex: "#ef4444" },
        { label: "Blue", value: "bg-blue-500", hex: "#3b82f6" },
        { label: "Green", value: "bg-green-500", hex: "#22c55e" },
        { label: "Yellow", value: "bg-yellow-400", hex: "#facc15" },
    ],
    fontWeight: [
        { label: "normal", value: '400' },
        { label: "bold", value: '500' },
        { label: "semibold", value: '600' },
        { label: "bolder", value: '700' },
        { label: "extrabold", value: '800' },
        { label: "light", value: '200' },
    ]
}
